import "./index.css"
import { Metadata } from "next"

export const metadata: Metadata = {
    title: {
        absolute: "",
        default: "Next.js 14 Training",
        template: "%s | Template title",
    },
    description: "Generated by Next.js",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <header
                    style={{
                        backgroundColor: "#9F84BD",
                        width: "100vw",
                        height: "5vw",
                        color: "white",
                        display: "flex",
                        alignItems: "center",
                    }}
                >
                    App Header
                </header>
                <div>{children}</div>
                <footer
                    style={{
                        backgroundColor: "#332E3C",
                        width: "100vw",
                        height: "5vw",
                        color: "white",
                        display: "flex",
                        alignItems: "center",
                        position: "fixed",
                        bottom: 0,
                    }}
                >
                    App Footer
                </footer>
            </body>
        </html>
    )
}
